CREATE TABLE Address(
    post_code NUMBER(10),
    city VARCHAR2(10) NOT NULL,
    town VARCHAR2(10) NOT NULL,
    area VARCHAR2(10) NOT NULL,
    CONSTRAINT address_addressid_pk PRIMARY KEY(post_code)
);

CREATE TABLE Department(

	department_id NUMBER GENERATED by default on null as IDENTITY(START with 10 INCREMENT by 10),
	department_name VARCHAR2(15),

	CONSTRAINT department_departmentid_pk PRIMARY KEY(department_id)
);
CREATE TABLE Room(

	room_id NUMBER GENERATED by default on null as IDENTITY(START with 1000 INCREMENT by 5),
	room_capacity NUMBER(2) NOT NULL CHECK (room_capacity < 4),
	status VARCHAR2(12) DEFAULT 'Available', 
	CONSTRAINT room_roomid_pk PRIMARY KEY(room_id)
	);


CREATE TABLE Employee(
	employee_id NUMBER GENERATED by default on null as IDENTITY(START with 1000 INCREMENT by 10),
	first_name VARCHAR2(10) NOT NULL,
	middle_name VARCHAR2(10),
	last_name VARCHAR2(10) NOT NULL,
	date_of_birth date NOT NULL,
	email VARCHAR2(75),
	post_code NUMBER(10),
	phone_number NUMBER(10) NOT NULL,
	job_title VARCHAR2(25) NOT NULL,
	date_of_starting_job date NOT NULL,
	manager_id NUMBER(10),
	department_id NUMBER(10) NOT NULL,
	CONSTRAINT employee_employeeid_pk PRIMARY KEY(employee_id),
	CONSTRAINT employee_managerid_fk FOREIGN KEY(manager_id) REFERENCES Employee(employee_id) ON DELETE SET NULL,
	CONSTRAINT employee_post_code_fk FOREIGN KEY(post_code) REFERENCES Address(post_code) ON DELETE CASCADE,
	CONSTRAINT employee_departmentid_fk FOREIGN KEY(department_id) REFERENCES Department(department_id) ON DELETE CASCADE
);




CREATE TABLE Salary(
    salary_id NUMBER GENERATED by default on null as IDENTITY(START with 1000 INCREMENT by 1),
	price NUMBER(7,2) CHECK (price > 0) NOT NULL,
	salary_date TIMESTAMP NOT NULL,
	hours_worked NUMBER(2) DEFAULT 8 NOT NULL,
	employee_id NUMBER(10) NOT NULL,
	CONSTRAINT salary_salaryid_pk PRIMARY KEY(salary_id),
	CONSTRAINT salary_employeeid_fk FOREIGN KEY(employee_id) REFERENCES Employee(employee_id) ON DELETE CASCADE
);

CREATE TABLE Service(
    service_id NUMBER GENERATED by default on null as IDENTITY(START with 1001 INCREMENT by 5) ,
    service_date TIMESTAMP NOT NULL,
    description VARCHAR2(255),
    status VARCHAR2(12)NOT NULL,
    room_id NUMBER(10) NOT NULL,
    department_id NUMBER(10) NOT NULL,
    
    PRIMARY KEY (service_id),
    CONSTRAINT FK_RoomService FOREIGN KEY (room_id) REFERENCES Room(room_id) ON DELETE CASCADE,
    CONSTRAINT FK_DeptService FOREIGN KEY (department_id) REFERENCES Department(department_id) ON DELETE CASCADE
    
);

CREATE TABLE Repair (
    service_id NUMBER(20) NOT NULL REFERENCES Service(service_id),
    item VARCHAR2(20),
    PRIMARY KEY(service_id)
);

CREATE TABLE Room_Cleaning (
    service_id NUMBER(20) NOT NULL REFERENCES Service(service_id),
    cleaning_type VARCHAR2(20),
    PRIMARY KEY(service_id)
);
CREATE TABLE Student(   
    student_id NUMBER(10) GENERATED by default on null as IDENTITY(START with 1000 INCREMENT by 1),   
    first_name  varchar(25) NOT NULL,   
    middle_name varchar(25),   
    last_name varchar(25) NOT NULL,   
    date_of_birth DATE NOT NULL,   
    email varchar(255) NOT NULL, 
    post_code NUMBER(6) NOT NULL,   
    phone_number varchar(15) NOT NULL,   
    school_department_name varchar(25) NOT NULL,   
    date_of_registration DATE NOT NULL,  
    bed_number NUMBER(4) NOT NULL,
    room_id NUMBER(10) NOT NULL,  
    PRIMARY KEY (student_id),
    CONSTRAINT student_roomid_fk FOREIGN KEY(room_id) REFERENCES Room(room_id) ON DELETE CASCADE,
CONSTRAINT student_post_code_fk FOREIGN KEY(post_code) REFERENCES Address(post_code) ON DELETE CASCADE
 );
 
CREATE TABLE Payment(
	payment_id NUMBER(10) GENERATED by default on null as IDENTITY(START with 1000 INCREMENT by 1),
	price NUMBER(7,2) NOT NULL CHECK (price > 0),
	payment_date TIMESTAMP,
	due_date TIMESTAMP NOT NULL ,
	status VARCHAR2(10) DEFAULT 'NOT PAID', 
	student_id NUMBER(10) NOT NULL,
	CONSTRAINT payment_paymentid_pk PRIMARY KEY(payment_id),
	CONSTRAINT payment_studentid_fk FOREIGN KEY(student_id) REFERENCES Student (student_id) ON DELETE CASCADE
);

CREATE OR REPLACE VIEW rooms AS (
SELECT
room.room_id, MAX(room_capacity) AS room_capacity ,MAX(status) AS room_status,
count(Student.room_id) AS registered_student,
MAX(room_capacity) - count(Student.room_id) AS available_bed_number
FROM Room
LEFT JOIN Student
ON student.room_id = room.room_id
GROUP BY room.room_id
);

CREATE OR REPLACE VIEW view_emp as(
SELECT Employee.employee_id, Employee.first_name, Employee.middle_name, Employee.last_name, Employee.date_of_birth, Employee.email,
Address.city, Address.town, Address.area, Address.post_code,
Employee.phone_number, Employee.job_title, Employee.date_of_starting_job, Employee.manager_id, Employee.department_id,
round(months_between(sysdate, date_of_birth)/12, 0) AS age
FROM Employee, Address
WHERE Address.post_code = Employee.post_code
);

CREATE OR REPLACE VIEW view_std as(
SELECT Student.student_id, Student.first_name, Student.middle_name, Student.last_name, Student.date_of_birth, Student.email,
Address.city, Address.town, Address.area, Address.post_code,
Student.phone_number, Student.school_department_name, Student.date_of_registration, Student.bed_number, Student.room_id,
round(months_between(sysdate, date_of_birth)/12, 0) AS age
FROM Student, Address
WHERE Address.post_code = Student.post_code
);

CREATE OR REPLACE VIEW Repair_Service AS
SELECT Repair.service_id ,Service.service_date, Repair.item, Service.description, Service.status, Service.room_id, Service.department_id FROM Repair ,Service
WHERE Repair.service_id = Service.service_id;
 
CREATE OR REPLACE VIEW Room_Cleaning_Service AS
SELECT Room_Cleaning.service_id ,Service.service_date, Room_Cleaning.cleaning_type, Service.description, Service.status, Service.room_id, Service.department_id FROM Room_Cleaning ,Service
WHERE Room_Cleaning.service_id = Service.service_id;

CREATE OR REPLACE  TRIGGER chk_full_room
before INSERT OR UPDATE on Student
for each row
declare
    available_beds varchar2(12);
    
begin
    select rooms.available_bed_number into available_beds
    from   rooms
    where  rooms.room_id= :new.room_id;

    if available_beds = 1 then 
        UPDATE room
        SET status = 'NTAVAIL'
        WHERE room.room_id = :NEW.room_id;
    END IF;
    
    if available_beds = 0 then
        UPDATE room
        SET status = 'NTAVAIL'
        WHERE room.room_id = :NEW.room_id;

        RAISE_APPLICATION_ERROR(-20005, 'Room is not available.');
    END IF;

END;
/

CREATE OR REPLACE TRIGGER chk_spent_years
BEFORE INSERT OR UPDATE on Student
FOR EACH ROW
BEGIN
DELETE FROM Student WHERE round(months_between(sysdate, date_of_registration)/12, 0) > 5;
END;
/


INSERT INTO Address(post_code, city, town, area) VALUES (35220, 'Izmir', 'Konak', 'Alsancak');
INSERT INTO Address(post_code, city, town, area) VALUES (35240, 'Izmir', 'Konak', 'Basmane');
INSERT INTO Address(post_code, city, town, area) VALUES (35270, 'Izmir', 'Konak', 'Esrefpasa');
INSERT INTO Address(post_code, city, town, area) VALUES (35190, 'Izmir', 'Konak', 'Gultepe');
INSERT INTO Address(post_code, city, town, area) VALUES (35180, 'Izmir', 'Konak', 'Gurcesme');
INSERT INTO Address(post_code, city, town, area) VALUES (35290, 'Izmir', 'Konak', 'Guzelyazı');
INSERT INTO Address(post_code, city, town, area) VALUES (35250, 'Izmir', 'Konak', 'Kemeralti');
INSERT INTO Address(post_code, city, town, area) VALUES (35530, 'Izmir', 'Karsiyaka', 'Karsiyaka');
INSERT INTO Address(post_code, city, town, area) VALUES (35550, 'Izmir', 'Karsiyaka', 'Yali');
INSERT INTO Address(post_code, city, town, area) VALUES (35560, 'Izmir', 'Karsiyaka', 'Nergiz');
INSERT INTO Address(post_code, city, town, area) VALUES (35570, 'Izmir', 'Karsiyaka', 'Cumhuriyet');
INSERT INTO Address(post_code, city, town, area) VALUES (35750, 'Izmir', 'Odemis', 'Demircili');
INSERT INTO Address(post_code, city, town, area) VALUES (35763, 'Izmir', 'Odemis', 'Koyler');
INSERT INTO Address(post_code, city, town, area) VALUES (35765, 'Izmir', 'Odemis', 'Kaymakci');
INSERT INTO Address(post_code, city, town, area) VALUES (35100, 'Izmir', 'Urla', 'Gulbahce');
INSERT INTO Address(post_code, city, town, area) VALUES (35200, 'Izmir', 'Urla', 'Torasan');
INSERT INTO Address(post_code, city, town, area) VALUES (35300, 'Izmir', 'Urla', 'Icmeler');
INSERT INTO Address(post_code, city, town, area) VALUES (35400, 'Izmir', 'Urla', 'Kuscular');
INSERT INTO Address(post_code, city, town, area) VALUES (35500, 'Izmir', 'Urla', 'Sirinkent');
INSERT INTO Address(post_code, city, town, area) VALUES (35600, 'Izmir', 'Urla', 'Yagcilar');
INSERT INTO Address(post_code, city, town, area) VALUES (35700, 'Izmir', 'Urla', 'Balikliova');
INSERT INTO Address(post_code, city, town, area) VALUES (06050, 'Ankara', 'Altindag', 'Opera ');
INSERT INTO Address(post_code, city, town, area) VALUES (06070, 'Ankara', 'Altindag', 'İskitler');
INSERT INTO Address(post_code, city, town, area) VALUES (06080, 'Ankara', 'Altindag', 'Altindag');
INSERT INTO Address(post_code, city, town, area) VALUES (07010, 'Antalya', 'Muratpasa', 'Eskisanayi');
INSERT INTO Address(post_code, city, town, area) VALUES (07040, 'Antalya', 'Muratpasa', 'Carsi' );

INSERT INTO room (room_capacity, status) VALUES (3, 'Available');
INSERT INTO room (room_capacity, status) VALUES (3, 'Available');
INSERT INTO room (room_capacity, status) VALUES (3, 'Available');
INSERT INTO room (room_capacity, status) VALUES (3, 'Available');
INSERT INTO room (room_capacity, status) VALUES (3, 'Available');
INSERT INTO room (room_capacity, status) VALUES (3, 'Available');
INSERT INTO room (room_capacity, status) VALUES (3, 'Available');
INSERT INTO room (room_capacity, status) VALUES (3, 'Available');
INSERT INTO room (room_capacity, status) VALUES (3, 'Available');
INSERT INTO room (room_capacity, status) VALUES (3, 'Available');
INSERT INTO room (room_capacity, status) VALUES (3, 'Available');
INSERT INTO room (room_capacity, status) VALUES (3, 'Available');
INSERT INTO room (room_capacity, status) VALUES (2, 'Available');
INSERT INTO room (room_capacity, status) VALUES (2, 'Available');
INSERT INTO room (room_capacity, status) VALUES (2, 'Available');
INSERT INTO room (room_capacity, status) VALUES (2, 'Available');
INSERT INTO room (room_capacity, status) VALUES (2, 'Available');
INSERT INTO room (room_capacity, status) VALUES (2, 'Available');
INSERT INTO room (room_capacity, status) VALUES (2, 'Available');
INSERT INTO room (room_capacity, status) VALUES (2, 'Available');
INSERT INTO room (room_capacity, status) VALUES (2, 'Available');
INSERT INTO room (room_capacity, status) VALUES (1, 'Available');
INSERT INTO room (room_capacity, status) VALUES (1, 'Available');
INSERT INTO room (room_capacity, status) VALUES (1, 'Available');
INSERT INTO room (room_capacity, status) VALUES (1, 'Available');

INSERT INTO Department(department_name) VALUES ('Management');
INSERT INTO Department(department_name) VALUES ('Maintenance');

INSERT INTO Student ( first_name, middle_name, last_name, date_of_birth,email,post_code, phone_number, school_department_name, date_of_registration, bed_number, room_id) VALUES ('Serdar',NULL,'Sertgoz', TO_DATE('1999/07/02', 'yyyy/mm/dd'), 'Serdar@gmail.com', 35100, 5423894567, 'Computer Engineering', TO_DATE('2018/07/02', 'yyyy/mm/dd') , 5,1000);
INSERT INTO Student ( first_name, middle_name, last_name, date_of_birth,email, post_code, phone_number, school_department_name, date_of_registration, bed_number, room_id) VALUES ('Ahmet',NULL,'Bas', TO_DATE('1999/09/05', 'yyyy/mm/dd'), 'Ahmet@gmail.com',35100, 5421234567, 'Chemical', TO_DATE('2018/07/02', 'yyyy/mm/dd') , 5,1005);
INSERT INTO Student ( first_name, middle_name, last_name, date_of_birth,email,post_code, phone_number, school_department_name, date_of_registration, bed_number, room_id) VALUES ('Mehmet',NULL,'Tas', TO_DATE('1997/07/02', 'yyyy/mm/dd'), 'Mehmet@gmail.com', 35100, 5423894567, 'Architect', TO_DATE('2016/07/02', 'yyyy/mm/dd') , 5,1010);
INSERT INTO Student ( first_name, middle_name, last_name, date_of_birth,email,post_code, phone_number, school_department_name, date_of_registration, bed_number, room_id) VALUES ('Mahmut',NULL,'Kel', TO_DATE('1997/07/02', 'yyyy/mm/dd'), 'Mahmut@gmail.com',35100, 5423894567, 'Math', TO_DATE('2017/07/02', 'yyyy/mm/dd') , 5,1015);
INSERT INTO Student ( first_name, middle_name, last_name, date_of_birth,email,post_code, phone_number, school_department_name, date_of_registration, bed_number, room_id) VALUES ('Ayse',NULL,'Sertgoz', TO_DATE('1998/05/02', 'yyyy/mm/dd'), 'Ayse@gmail.com', 35100, 5423894567, 'Physic', TO_DATE('2019/04/02', 'yyyy/mm/dd') , 5,1020);
INSERT INTO Student ( first_name, middle_name, last_name, date_of_birth,email,post_code, phone_number, school_department_name, date_of_registration, bed_number, room_id) VALUES ('Fatma',NULL,'Uyuz', TO_DATE('1999/07/02', 'yyyy/mm/dd'), 'Fatma@gmail.com',35100, 5423894567, 'Computer', TO_DATE('2018/07/02', 'yyyy/mm/dd') , 5,1025);
INSERT INTO Student ( first_name, middle_name, last_name, date_of_birth,email,post_code, phone_number, school_department_name, date_of_registration, bed_number, room_id) VALUES ('Huriye',NULL,'Kil', TO_DATE('2000/07/02', 'yyyy/mm/dd'), 'Huriye@gmail.com', 35100, 5423894567, 'Bioengineering', TO_DATE('2018/07/02', 'yyyy/mm/dd') , 5,1030);
INSERT INTO Student ( first_name, middle_name, last_name, date_of_birth,email,post_code, phone_number, school_department_name, date_of_registration, bed_number, room_id) VALUES ('Harun','Ermez','Mutsuz', TO_DATE('1999/07/02', 'yyyy/mm/dd'), 'Harun@gmail.com',35100, 5423894567, 'Computer', TO_DATE('2018/07/02', 'yyyy/mm/dd') , 5,1035);
INSERT INTO Student ( first_name, middle_name, last_name, date_of_birth,email,post_code, phone_number, school_department_name, date_of_registration, bed_number, room_id) VALUES ('Ertugrul',NULL,'Bakir', TO_DATE('1999/07/02', 'yyyy/mm/dd'), 'Ertugrul@gmail.com',35100, 5423894567, 'Machine Engineering', TO_DATE('2018/06/02', 'yyyy/mm/dd') , 5,1040);
INSERT INTO Student ( first_name, middle_name, last_name, date_of_birth,email,post_code, phone_number, school_department_name, date_of_registration, bed_number, room_id) VALUES ('Abdul',NULL,'Kaymaz', TO_DATE('1996/07/02', 'yyyy/mm/dd'), 'Abdul@gmail.com', 35100, 5423894567, 'Chemical', TO_DATE('2019/07/02', 'yyyy/mm/dd') , 5,1045);
INSERT INTO Student ( first_name, middle_name, last_name, date_of_birth,email,post_code, phone_number, school_department_name, date_of_registration, bed_number, room_id) VALUES ('Muhittin',NULL,'Gezer', TO_DATE('1999/02/22', 'yyyy/mm/dd'), 'Muhittin@gmail.com', 35100, 5423891700, 'Physic', TO_DATE('2018/07/02', 'yyyy/mm/dd') , 5,1050);
INSERT INTO Student ( first_name, middle_name, last_name, date_of_birth,email,post_code, phone_number, school_department_name, date_of_registration, bed_number, room_id) VALUES ('Selahattin',NULL,'Ay', TO_DATE('1999/07/02', 'yyyy/mm/dd'), 'Selahattin@gmail.com', 35100, 5423894567, 'Bioengineering', TO_DATE('2019/07/02', 'yyyy/mm/dd') , 5,1055);
INSERT INTO Student ( first_name, middle_name, last_name, date_of_birth,email,post_code, phone_number, school_department_name, date_of_registration, bed_number, room_id) VALUES ('Mumin',NULL,'Of', TO_DATE('1999/07/02', 'yyyy/mm/dd'), 'Mumin@gmail.com',35100, 5423894567, 'Computer', TO_DATE('2020/07/02', 'yyyy/mm/dd') , 5,1060);
INSERT INTO Student ( first_name, middle_name, last_name, date_of_birth,email,post_code, phone_number, school_department_name, date_of_registration, bed_number, room_id) VALUES ('Kerim',NULL,'Aydin', TO_DATE('1998/11/02', 'yyyy/mm/dd'), 'Kerim@gmail.com', 35100, 5423894567, 'Architect', TO_DATE('2020/08/02', 'yyyy/mm/dd') , 5,1065);
INSERT INTO Student ( first_name, middle_name, last_name, date_of_birth,email,post_code, phone_number, school_department_name, date_of_registration, bed_number, room_id) VALUES ('Saffet',NULL,'Reis', TO_DATE('1999/07/02', 'yyyy/mm/dd'), 'Saffet@gmail.com', 35100, 5423894567, 'Chemical', TO_DATE('2018/07/02', 'yyyy/mm/dd') , 5,1000);
INSERT INTO Student ( first_name, middle_name, last_name, date_of_birth,email,post_code, phone_number, school_department_name, date_of_registration, bed_number, room_id) VALUES ('Selami',NULL,'Sahin', TO_DATE('1999/07/02', 'yyyy/mm/dd'), 'Selami@gmail.com', 35100, 5423891700, 'Math', TO_DATE('2018/07/02', 'yyyy/mm/dd') , 5,1050);
INSERT INTO Student ( first_name, middle_name, last_name, date_of_birth,email,post_code, phone_number, school_department_name, date_of_registration, bed_number, room_id) VALUES ('Yusuf',NULL,'Dondu', TO_DATE('1997/07/02', 'yyyy/mm/dd'), 'Yusuf@gmail.com',35100, 5423894567, 'Architect', TO_DATE('2016/07/02', 'yyyy/mm/dd') , 5,1080);
INSERT INTO Student ( first_name, middle_name, last_name, date_of_birth,email,post_code, phone_number, school_department_name, date_of_registration, bed_number, room_id) VALUES ('Haydar',NULL,'Bas', TO_DATE('1999/07/02 ', 'yyyy/mm/dd'), 'Haydar@gmail.com',35100, 5423894567, 'History', TO_DATE('2018/07/02 ', 'yyyy/mm/dd') , 5,1040);
INSERT INTO Student ( first_name, middle_name, last_name, date_of_birth,email,post_code, phone_number, school_department_name, date_of_registration, bed_number, room_id) VALUES ('Yakub',NULL,'Bacanak', TO_DATE('1999/07/02', 'yyyy/mm/dd'), 'Yakub@gmail.com', 35100, 5423894567, 'History', TO_DATE('2018/07/02 ', 'yyyy/mm/dd') , 5,1030);
INSERT INTO Student ( first_name, middle_name, last_name, date_of_birth,email,post_code, phone_number, school_department_name, date_of_registration, bed_number, room_id) VALUES ('Ummani',NULL,'Saf', TO_DATE('1999/07/02', 'yyyy/mm/dd'), 'Ummani@gmail.com', 35100, 5423891700, 'Bioengineering', TO_DATE('2018/07/02', 'yyyy/mm/dd') , 5,1035);
INSERT INTO Student ( first_name, middle_name, last_name, date_of_birth,email, post_code, phone_number, school_department_name, date_of_registration, bed_number, room_id) VALUES ('Hayat',NULL,'Zor', TO_DATE('2000/04/22', 'yyyy/mm/dd'), 'Hayat@gmail.com', 35100, 5423894567, 'Computer', TO_DATE('2018/07/02', 'yyyy/mm/dd') , 5,1020);
INSERT INTO Student ( first_name, middle_name, last_name, date_of_birth,email,post_code, phone_number, school_department_name, date_of_registration, bed_number, room_id) VALUES ('Yasin',NULL,'Bakir', TO_DATE('1999/07/02', 'yyyy/mm/dd'), 'Ertugrul@gmail.com',35100, 5423894567, 'Machine Engineering', TO_DATE('2018/06/02', 'yyyy/mm/dd') , 5,1040);
INSERT INTO Student ( first_name, middle_name, last_name, date_of_birth,email,post_code, phone_number, school_department_name, date_of_registration, bed_number, room_id) VALUES ('Osman',NULL,'Kaymaz', TO_DATE('1996/07/02', 'yyyy/mm/dd'), 'Abdul@gmail.com', 35100, 5423894567, 'Chemical', TO_DATE('2019/07/02', 'yyyy/mm/dd') , 5,1045);
INSERT INTO Student ( first_name, middle_name, last_name, date_of_birth,email,post_code, phone_number, school_department_name, date_of_registration, bed_number, room_id) VALUES ('Mert',NULL,'Gezer', TO_DATE('1999/02/22', 'yyyy/mm/dd'), 'Muhittin@gmail.com', 35100, 5423891700, 'Physic', TO_DATE('2018/07/02', 'yyyy/mm/dd') , 5,1050);
INSERT INTO Student ( first_name, middle_name, last_name, date_of_birth,email,post_code, phone_number, school_department_name, date_of_registration, bed_number, room_id) VALUES ('Furkan',NULL,'Ay', TO_DATE('1999/07/02', 'yyyy/mm/dd'), 'Selahattin@gmail.com', 35100, 5423894567, 'Bioengineering', TO_DATE('2019/07/02', 'yyyy/mm/dd') , 5,1055);

INSERT INTO Employee (first_name, middle_name, last_name,date_of_birth, email,post_code, phone_number, job_title, date_of_starting_job, manager_id, department_id)
 VALUES ('Harun', 'Eren', 'MUTLU', TO_DATE('1972/07/13', 'yyyy/mm/dd'), 'harunmutlu@dorm.iyte.edu.tr', 35100, 5458429381, 'Head Of Dormitory', TO_DATE('2020/05/03', 'yyyy/mm/dd'), NULL, 10);

INSERT INTO Employee (first_name, middle_name, last_name,date_of_birth, email, post_code, phone_number, job_title, date_of_starting_job, manager_id, department_id)
 VALUES ('Merve', NULL, 'MALAK', TO_DATE('1972/03/21', 'yyyy/mm/dd'), 'mervemalak@dorm.iyte.edu.tr', 35100, 5452571562, 'Student Affair', TO_DATE('2020/02/15', 'yyyy/mm/dd'), 1000, 10);

INSERT INTO Employee (first_name, middle_name, last_name,date_of_birth, email, post_code, phone_number, job_title, date_of_starting_job, manager_id, department_id)
 VALUES ('Gozde', NULL, 'KURTULMUS', TO_DATE('1973/06/09', 'yyyy/mm/dd'), 'gozdekurtulmus@dorm.iyte.edu.tr', 35100, 5456792491, 'Student Affair', TO_DATE('2021/08/10', 'yyyy/mm/dd'), 1000, 10);

INSERT INTO Employee (first_name, middle_name, last_name,date_of_birth, email, post_code, phone_number, job_title, date_of_starting_job, manager_id, department_id)
 VALUES ('Serdar', NULL, 'SERTGOZ', TO_DATE('1970/07/13', 'yyyy/mm/dd'), 'serdarsertgoz@dorm.iyte.edu.tr', 35100, 5451793846, 'Administrative Officer', TO_DATE('2020/11/19', 'yyyy/mm/dd'), 1000, 10);

INSERT INTO Employee (first_name, middle_name, last_name,date_of_birth, email, post_code, phone_number, job_title, date_of_starting_job, manager_id, department_id)
 VALUES ('Ertugrul', NULL, 'DEMIR', TO_DATE('1972/10/10', 'yyyy/mm/dd'), 'ertdemir@dorm.iyte.edu.tr', 35100, 5458729671, 'Administrative Officer', TO_DATE('2020/10/23', 'yyyy/mm/dd'), 1000, 10);

INSERT INTO Employee (first_name, middle_name, last_name,date_of_birth, email, post_code, phone_number, job_title, date_of_starting_job, manager_id, department_id)
 VALUES ('Hakki', NULL, 'YETEN', TO_DATE('1955/10/28', 'yyyy/mm/dd'), 'hakkiyeten@dorm.iyte.edu.tr', 35100, 9817392843, 'Head Of Repair', TO_DATE('2008/07/10', 'yyyy/mm/dd'), 1030, 20);

INSERT INTO Employee (first_name, middle_name, last_name,date_of_birth, email, post_code, phone_number, job_title, date_of_starting_job, manager_id, department_id)
 VALUES ('Sakine', 'Muberra', 'HAYIRSIZ', TO_DATE('1968/12/06', 'yyyy/mm/dd'), 'sakinehayirsiz@dorm.iyte.edu.tr', 35100, 4682493821, 'Head Of Cleaning', TO_DATE('2009/09/13', 'yyyy/mm/dd'), 1040, 20);

INSERT INTO Employee (first_name, middle_name, last_name,date_of_birth, email,post_code, phone_number, job_title, date_of_starting_job, manager_id, department_id)
 VALUES ('Bihter', NULL, 'ZIYAGIL', TO_DATE('1970/02/19', 'yyyy/mm/dd'), 'bihterziyagil@dorm.iyte.edu.tr', 35100, 7618349521, 'Cleaning Staff', TO_DATE('2012/08/15', 'yyyy/mm/dd'), 1060, 20);

INSERT INTO Employee (first_name, middle_name, last_name,date_of_birth, email,post_code, phone_number, job_title, date_of_starting_job, manager_id, department_id)
 VALUES ('Kuzey', NULL, 'TEKINOGLU', TO_DATE('1978/11/07', 'yyyy/mm/dd'), 'kuzeytekinoglu@dorm.iyte.edu.tr', 35100, 9762843185, 'Repair Staff', TO_DATE('2013/02/03', 'yyyy/mm/dd'), 1050, 20);

INSERT INTO Employee (first_name, middle_name, last_name,date_of_birth, email, post_code, phone_number, job_title, date_of_starting_job, manager_id, department_id)
 VALUES ('Polat', 'Omer', 'ALEMDAR', TO_DATE('1980/01/20', 'yyyy/mm/dd'), 'polatalemdar@dorm.iyte.edu.tr', 35100, 7568139456, 'Cleaning Staff', TO_DATE('2014/03/13', 'yyyy/mm/dd'), 1060, 20);

INSERT INTO Employee (first_name, middle_name, last_name,date_of_birth, email, post_code, phone_number, job_title, date_of_starting_job, manager_id, department_id)
 VALUES ('Memati', NULL, 'BAS', TO_DATE('1981/08/12', 'yyyy/mm/dd'), 'mematibas@dorm.iyte.edu.tr', 35100, 5486921782, 'Cleaning Staff', TO_DATE('2011/04/08', 'yyyy/mm/dd'), 1060, 20);

INSERT INTO Employee (first_name, middle_name, last_name,date_of_birth, email,post_code, phone_number, job_title, date_of_starting_job, manager_id, department_id)
 VALUES ('Oguzhan', NULL, 'MERTTURK', TO_DATE('1973/12/03', 'yyyy/mm/dd'), 'oguzhanmertturk@dorm.iyte.edu.tr',35100, 4787569182, 'Cleaning Staff', TO_DATE('2012/11/11', 'yyyy/mm/dd'), 1060, 20);

INSERT INTO Employee (first_name, middle_name, last_name,date_of_birth, email, post_code, phone_number, job_title, date_of_starting_job, manager_id, department_id)
 VALUES ('Abdulhey', NULL, 'COBAN', TO_DATE('1984/02/11', 'yyyy/mm/dd'), 'abdulheycoban@dorm.iyte.edu.tr', 35100, 1975684399, 'Cleaning Staff', TO_DATE('2019/10/17', 'yyyy/mm/dd'),1060, 20);

INSERT INTO Employee (first_name, middle_name, last_name,date_of_birth, email,post_code, phone_number, job_title, date_of_starting_job, manager_id, department_id)
 VALUES ('Ramiz', NULL, 'KARAESKI', TO_DATE('1965/11/11', 'yyyy/mm/dd'), 'ramizkaraeski@dorm.iyte.edu.tr',35100, 6785439288, 'Cleaning Staff', TO_DATE('2020/05/19', 'yyyy/mm/dd'), 1060, 20);

INSERT INTO Employee (first_name, middle_name, last_name,date_of_birth, email, post_code, phone_number, job_title, date_of_starting_job, manager_id, department_id)
 VALUES ('Hain', NULL, 'KOSTOK', TO_DATE('1988/09/18', 'yyyy/mm/dd'), 'hainkostok@dorm.iyte.edu.tr', 35100, 1675298436, 'Repair Staff', TO_DATE('2021/09/28', 'yyyy/mm/dd'), 1050, 20);

INSERT INTO Employee (first_name, middle_name, last_name,date_of_birth, email, post_code, phone_number, job_title, date_of_starting_job, manager_id, department_id)
 VALUES ('Burhan', NULL, 'ALTINTOP', TO_DATE('1990/02/09', 'yyyy/mm/dd'), 'burhanaltintop@dorm.iyte.edu.tr', 35100, 8542395462, 'Repair Staff', TO_DATE('2017/10/07', 'yyyy/mm/dd'), 1050, 20);

INSERT INTO Employee (first_name, middle_name, last_name,date_of_birth, email, post_code, phone_number, job_title, date_of_starting_job, manager_id, department_id)
 VALUES ('Erdal', NULL, 'BAKKAL', TO_DATE('1972/05/28', 'yyyy/mm/dd'), 'erdalbakkal@dorm.iyte.edu.tr', 35100, 2468271691, 'Repair Staff', TO_DATE('2010/12/22', 'yyyy/mm/dd'), 1050, 20);

INSERT INTO Employee (first_name, middle_name, last_name,date_of_birth, email,post_code, phone_number, job_title, date_of_starting_job, manager_id, department_id)
 VALUES ('Suleyman', NULL, 'Cakir', TO_DATE('1962/01/01', 'yyyy/mm/dd'), 'suleymancakir@dorm.iyte.edu.tr', 35100, 1976492671, 'Cleaning Staff', TO_DATE('2010/10/11', 'yyyy/mm/dd'), 1060, 20);

INSERT INTO Employee (first_name, middle_name, last_name,date_of_birth, email, post_code, phone_number, job_title, date_of_starting_job, manager_id, department_id)
 VALUES ('Hurrem', NULL, 'SULTAN', TO_DATE('1970/08/20', 'yyyy/mm/dd'), 'hurremsultan@dorm.iyte.edu.tr', 35100, 2964820168, 'Cleaning Staff', TO_DATE('2018/07/20', 'yyyy/mm/dd'), 1060, 20);

INSERT INTO Employee (first_name, middle_name, last_name,date_of_birth, email,post_code, phone_number, job_title, date_of_starting_job, manager_id, department_id)
 VALUES ('Suleyman', 'Kanuni', 'SULTAN', TO_DATE('1965/04/19', 'yyyy/mm/dd'), 'kanunisuleymansultan@dorm.iyte.edu.tr', 35100, 1925762849, 'Repair Staff', TO_DATE('2009/09/11', 'yyyy/mm/dd'), 1050, 20);

INSERT INTO Employee (first_name, middle_name, last_name,date_of_birth, email, post_code, phone_number, job_title, date_of_starting_job, manager_id, department_id)
 VALUES ('Mevlana', 'Celaleddin', 'RUMI', TO_DATE('1986/10/26', 'yyyy/mm/dd'), 'mevlanarumi@dorm.iyte.edu.tr', 35100, 6926842619, 'Repair Staff', TO_DATE('2010/11/01', 'yyyy/mm/dd'), 1050, 20);

INSERT INTO Employee (first_name, middle_name, last_name,date_of_birth, email, post_code, phone_number, job_title, date_of_starting_job, manager_id, department_id)
 VALUES ('Yunus', 'Emre', 'BILGE', TO_DATE('1987/08/25', 'yyyy/mm/dd'), 'yunusbilge@dorm.iyte.edu.tr', 35100, 2874913664, 'Repair Staff', TO_DATE('2019/11/08', 'yyyy/mm/dd'), 1050, 20);

INSERT INTO Service(service_date, description, status, room_id,department_id) VALUES ( TO_TIMESTAMP('2019/02/06 23:58:28','yyyy/mm/dd hh24:mi:ss'),'Tikaniklik giderildi.', 'COMPLETE', 1000,20);
INSERT INTO Repair(item,service_id) VALUES ('LAVABO',(SELECT service_id FROM Service WHERE service_id = (SELECT MAX(service_id) FROM Service)));
INSERT INTO Service(service_date, description, status, room_id,department_id) VALUES ( TO_TIMESTAMP('2019/02/08 23:49:34','yyyy/mm/dd hh24:mi:ss'),'Dus basligi degistirildi.', 'COMPLETE', 1000,20);
INSERT INTO Repair(item,service_id) VALUES ('DUS BASLIGI',(SELECT service_id FROM Service WHERE service_id = (SELECT MAX(service_id) FROM Service)));
INSERT INTO Service(service_date, description, status, room_id,department_id) VALUES ( TO_TIMESTAMP('2019/02/14 12:00:32','yyyy/mm/dd hh24:mi:ss'),'Banyo tamamen temizlendi.', 'COMPLETE', 1020,20);
INSERT INTO Room_Cleaning (cleaning_type,service_id) VALUES ('BANYO',(SELECT service_id FROM Service WHERE service_id = (SELECT MAX(service_id) FROM Service)));
INSERT INTO Service(service_date, description, status, room_id,department_id) VALUES ( TO_TIMESTAMP('2019/03/08 03:54:57','yyyy/mm/dd hh24:mi:ss'),'Havasi giderildi.', 'COMPLETE', 1035,20);
INSERT INTO Repair(item,service_id) VALUES ('KALORIFER PETEGI',(SELECT service_id FROM Service WHERE service_id = (SELECT MAX(service_id) FROM Service)));
INSERT INTO Service(service_date, description, status, room_id,department_id) VALUES ( TO_TIMESTAMP('2019/04/24 05:33:09','yyyy/mm/dd hh24:mi:ss'),'Havasi giderildi.', 'COMPLETE', 1015,20);
INSERT INTO Repair(item,service_id) VALUES ('KALORIFER PETEGI',(SELECT service_id FROM Service WHERE service_id = (SELECT MAX(service_id) FROM Service)));
INSERT INTO Service(service_date, description, status, room_id,department_id) VALUES ( TO_TIMESTAMP('2019/11/01 04:17:23','yyyy/mm/dd hh24:mi:ss'),'Oda temizlendi.', 'COMPLETE', 1040,20);
INSERT INTO Room_Cleaning (cleaning_type,service_id) VALUES ('ODA',(SELECT service_id FROM Service WHERE service_id = (SELECT MAX(service_id) FROM Service)));
INSERT INTO Service(service_date, description, status, room_id,department_id) VALUES ( TO_TIMESTAMP('2020/05/14 01:06:14','yyyy/mm/dd hh24:mi:ss'),NULL, 'UNCOMPLETE', 1040,20);
INSERT INTO Repair(item,service_id) VALUES ('BALKON LAMBASI',(SELECT service_id FROM Service WHERE service_id = (SELECT MAX(service_id) FROM Service)));
INSERT INTO Service(service_date, description, status, room_id,department_id) VALUES ( TO_TIMESTAMP('2020/07/31 04:01:21','yyyy/mm/dd hh24:mi:ss'),NULL, 'UNCOMPLETE', 1020,20);
INSERT INTO Room_Cleaning (cleaning_type,service_id) VALUES ('BALKON',(SELECT service_id FROM Service WHERE service_id = (SELECT MAX(service_id) FROM Service)));
INSERT INTO Service(service_date, description, status, room_id,department_id) VALUES ( TO_TIMESTAMP('2020/08/16 07:07:03','yyyy/mm/dd hh24:mi:ss'),NULL, 'UNCOMPLETE', 1080,20);
INSERT INTO Room_Cleaning (cleaning_type,service_id) VALUES ('BALKON',(SELECT service_id FROM Service WHERE service_id = (SELECT MAX(service_id) FROM Service)));
INSERT INTO Service(service_date, description, status, room_id,department_id) VALUES ( TO_TIMESTAMP('2020/08/30 06:22:19','yyyy/mm/dd hh24:mi:ss'),NULL, 'UNCOMPLETE', 1090,20);
INSERT INTO Room_Cleaning (cleaning_type,service_id) VALUES ('BALKON',(SELECT service_id FROM Service WHERE service_id = (SELECT MAX(service_id) FROM Service)));
INSERT INTO Service(service_date, description, status, room_id,department_id) VALUES ( TO_TIMESTAMP('2020/12/15 11:50:43','yyyy/mm/dd hh24:mi:ss'),'Gerekli malzeme tedarik ediliyor.', 'ON-HOLD', 1065,20);
INSERT INTO Repair(item,service_id) VALUES ('FAYANS',(SELECT service_id FROM Service WHERE service_id = (SELECT MAX(service_id) FROM Service)));
INSERT INTO Service(service_date, description, status, room_id,department_id) VALUES ( TO_TIMESTAMP('2021/01/24 15:52:30','yyyy/mm/dd hh24:mi:ss'),'Gerekli malzeme tedarik ediliyor.', 'ON-HOLD', 1045,20);
INSERT INTO Repair(item,service_id) VALUES ('FAYANS',(SELECT service_id FROM Service WHERE service_id = (SELECT MAX(service_id) FROM Service)));
INSERT INTO Service(service_date, description, status, room_id,department_id) VALUES ( TO_TIMESTAMP('2021/02/10 19:34:49','yyyy/mm/dd hh24:mi:ss'),'Oda tadilatta.', 'ON-HOLD', 1055,20);
INSERT INTO Room_Cleaning (cleaning_type,service_id) VALUES ('BANYO',(SELECT service_id FROM Service WHERE service_id = (SELECT MAX(service_id) FROM Service)));
INSERT INTO Service(service_date, description, status, room_id,department_id) VALUES ( TO_TIMESTAMP('2021/02/27 05:50:23','yyyy/mm/dd hh24:mi:ss'),'Oda tadilatta.', 'ON-HOLD', 1035,20);
INSERT INTO Room_Cleaning (cleaning_type,service_id) VALUES ('BANYO',(SELECT service_id FROM Service WHERE service_id = (SELECT MAX(service_id) FROM Service)));
INSERT INTO Service(service_date, description, status, room_id,department_id) VALUES ( TO_TIMESTAMP('2021/03/01 20:22:01','yyyy/mm/dd hh24:mi:ss'),'Gerekli malzeme tedarik ediliyor.', 'ON-HOLD', 1015,20);
INSERT INTO Repair(item,service_id) VALUES ('DUVAR',(SELECT service_id FROM Service WHERE service_id = (SELECT MAX(service_id) FROM Service)));
INSERT INTO Service(service_date, description, status, room_id,department_id) VALUES ( TO_TIMESTAMP('2021/10/14 01:21:13','yyyy/mm/dd hh24:mi:ss'),NULL, 'IN-PROGRESS', 1005,20);
INSERT INTO Repair(item,service_id) VALUES ('BAZA',(SELECT service_id FROM Service WHERE service_id = (SELECT MAX(service_id) FROM Service)));
INSERT INTO Service(service_date, description, status, room_id,department_id) VALUES ( TO_TIMESTAMP('2021/10/15 00:10:18','yyyy/mm/dd hh24:mi:ss'),NULL, 'IN-PROGRESS', 1075,20);
INSERT INTO Room_Cleaning (cleaning_type,service_id) VALUES ('ODA',(SELECT service_id FROM Service WHERE service_id = (SELECT MAX(service_id) FROM Service)));
INSERT INTO Service(service_date, description, status, room_id,department_id) VALUES ( TO_TIMESTAMP('2021/10/16 01:59:25','yyyy/mm/dd hh24:mi:ss'),NULL, 'IN-PROGRESS', 1070,20);
INSERT INTO Room_Cleaning (cleaning_type,service_id) VALUES ('BANYO',(SELECT service_id FROM Service WHERE service_id = (SELECT MAX(service_id) FROM Service)));
INSERT INTO Service(service_date, description, status, room_id,department_id) VALUES ( TO_TIMESTAMP('2021/10/22 18:48:38','yyyy/mm/dd hh24:mi:ss'),NULL, 'IN-PROGRESS', 1080,20);
INSERT INTO Repair(item,service_id) VALUES ('DUS BASLIGI',(SELECT service_id FROM Service WHERE service_id = (SELECT MAX(service_id) FROM Service)));
INSERT INTO Service(service_date, description, status, room_id,department_id) VALUES ( TO_TIMESTAMP('2021/10/23 11:53:16','yyyy/mm/dd hh24:mi:ss'),NULL, 'IN-PROGRESS', 1050,20);

INSERT INTO Room_Cleaning (cleaning_type,service_id) VALUES ('ODA',(SELECT service_id FROM Service WHERE service_id = (SELECT MAX(service_id) FROM Service)));
INSERT INTO Salary(price, salary_date, hours_worked, employee_id) VALUES (1000, TO_TIMESTAMP('2017/07/02 06:14:14','yyyy/mm/dd hh24:mi:ss'), 8, 1000) ;
INSERT INTO Salary(price, salary_date, hours_worked, employee_id) VALUES (1050, TO_TIMESTAMP('2017/08/02 06:18:14','yyyy/mm/dd hh24:mi:ss'), 9, 1010) ;
INSERT INTO Salary(price, salary_date, hours_worked, employee_id) VALUES (1520, TO_TIMESTAMP('2017/10/02 06:25:14','yyyy/mm/dd hh24:mi:ss'), 8, 1020) ;
INSERT INTO Salary(price, salary_date, hours_worked, employee_id) VALUES (9000, TO_TIMESTAMP('2018/01/09 11:14:14','yyyy/mm/dd hh24:mi:ss'), 7, 1030) ;
INSERT INTO Salary(price, salary_date, hours_worked, employee_id) VALUES (8000, TO_TIMESTAMP('2018/02/22 12:14:13','yyyy/mm/dd hh24:mi:ss'), 6, 1040) ;
INSERT INTO Salary(price, salary_date, hours_worked, employee_id) VALUES (7550, TO_TIMESTAMP('2018/04/12 08:15:14','yyyy/mm/dd hh24:mi:ss'), 5, 1050) ;
INSERT INTO Salary(price, salary_date, hours_worked, employee_id) VALUES (4852, TO_TIMESTAMP('2018/07/02 14:14:14','yyyy/mm/dd hh24:mi:ss'), 8, 1060) ;
INSERT INTO Salary(price, salary_date, hours_worked, employee_id) VALUES (4600, TO_TIMESTAMP('2018/12/05 23:14:14','yyyy/mm/dd hh24:mi:ss'), 8, 1070) ;
INSERT INTO Salary(price, salary_date, hours_worked, employee_id) VALUES (4500, TO_TIMESTAMP('2019/03/02 16:14:14','yyyy/mm/dd hh24:mi:ss'), 8, 1080) ;
INSERT INTO Salary(price, salary_date, hours_worked, employee_id) VALUES (9874, TO_TIMESTAMP('2019/05/02 12:14:35','yyyy/mm/dd hh24:mi:ss'), 9, 1090) ;
INSERT INTO Salary(price, salary_date, hours_worked, employee_id) VALUES (1236, TO_TIMESTAMP('2019/07/02 06:14:14','yyyy/mm/dd hh24:mi:ss'), 10, 1100) ;
INSERT INTO Salary(price, salary_date, hours_worked, employee_id) VALUES (1234, TO_TIMESTAMP('2020/05/30 18:17:15','yyyy/mm/dd hh24:mi:ss'), 10, 1110) ;
INSERT INTO Salary(price, salary_date, hours_worked, employee_id) VALUES (7532, TO_TIMESTAMP('2020/08/01 08:14:14','yyyy/mm/dd hh24:mi:ss'), 11, 1120) ;
INSERT INTO Salary(price, salary_date, hours_worked, employee_id) VALUES (8524, TO_TIMESTAMP('2020/11/05 06:14:14','yyyy/mm/dd hh24:mi:ss'), 11, 1130) ;
INSERT INTO Salary(price, salary_date, hours_worked, employee_id) VALUES (1620, TO_TIMESTAMP('2021/10/10 10:10:10','yyyy/mm/dd hh24:mi:ss'), 10, 1140) ;
INSERT INTO Salary(price, salary_date, hours_worked, employee_id) VALUES (1100, TO_TIMESTAMP('2021/12/21 12:12:12','yyyy/mm/dd hh24:mi:ss'), 9, 1150) ;
INSERT INTO Salary(price, salary_date, hours_worked, employee_id) VALUES (1000, TO_TIMESTAMP('2021/01/02 15:14:14','yyyy/mm/dd hh24:mi:ss'), 8, 1160) ;
INSERT INTO Salary(price, salary_date, hours_worked, employee_id) VALUES (2000, TO_TIMESTAMP('2021/02/05 14:15:14','yyyy/mm/dd hh24:mi:ss'), 8, 1170) ;
INSERT INTO Salary(price, salary_date, hours_worked, employee_id) VALUES (6000, TO_TIMESTAMP('2021/05/08 15:15:35','yyyy/mm/dd hh24:mi:ss'), 8, 1180) ;
INSERT INTO Salary(price, salary_date, hours_worked, employee_id) VALUES (5000, TO_TIMESTAMP('2021/07/02 20:15:14','yyyy/mm/dd hh24:mi:ss'), 8, 1190) ;
INSERT INTO Salary(price, salary_date, hours_worked, employee_id) VALUES (4000, TO_TIMESTAMP('2021/08/02 11:14:14','yyyy/mm/dd hh24:mi:ss'), 8, 1200) ;

INSERT INTO Payment (price, payment_date, due_date, status, student_id) VALUES (500,  NULL, TO_TIMESTAMP('2018/02/05 12:14:14','yyyy/mm/dd hh24:mi:ss') , 'NOT PAID', 1000);
INSERT INTO Payment (price, payment_date, due_date, status, student_id) VALUES (550,  TO_TIMESTAMP('2018/03/04 14:14:14','yyyy/mm/dd hh24:mi:ss'), TO_TIMESTAMP('2018/03/05 14:12:14','yyyy/mm/dd hh24:mi:ss') , 'PAID', 1001);
INSERT INTO Payment (price, payment_date, due_date, status, student_id) VALUES (250,  NULL, TO_TIMESTAMP('2018/05/05 12:15:14','yyyy/mm/dd hh24:mi:ss') , 'NOT PAID', 1002);
INSERT INTO Payment (price, payment_date, due_date, status, student_id) VALUES (450,  TO_TIMESTAMP('2018/07/08 15:14:15','yyyy/mm/dd hh24:mi:ss'), TO_TIMESTAMP('2018/07/09 12:12:12','yyyy/mm/dd hh24:mi:ss') , 'PAID', 1003);
INSERT INTO Payment (price, payment_date, due_date, status, student_id) VALUES (180,  NULL, TO_TIMESTAMP('2018/08/05 19:14:14','yyyy/mm/dd hh24:mi:ss') , 'NOT PAID', 1004);
INSERT INTO Payment (price, payment_date, due_date, status, student_id) VALUES (480,  TO_TIMESTAMP('2019/01/02 05:14:05','yyyy/mm/dd hh24:mi:ss'), TO_TIMESTAMP('2019/01/08 08:14:14','yyyy/mm/dd hh24:mi:ss') , 'PAID', 1005);
INSERT INTO Payment (price, payment_date, due_date, status, student_id) VALUES (225,  NULL, TO_TIMESTAMP('2019/02/05 18:14:14','yyyy/mm/dd hh24:mi:ss') , 'NOT PAID', 1006);
INSERT INTO Payment (price, payment_date, due_date, status, student_id) VALUES (250,  TO_TIMESTAMP('2019/07/02 06:14:14','yyyy/mm/dd hh24:mi:ss'), TO_TIMESTAMP('2019/07/05 15:14:14','yyyy/mm/dd hh24:mi:ss') , 'PAID', 1007);
INSERT INTO Payment (price, payment_date, due_date, status, student_id) VALUES (240,  NULL, TO_TIMESTAMP('2019/09/25 22:10:14','yyyy/mm/dd hh24:mi:ss') , 'NOT PAID', 1008);
INSERT INTO Payment (price, payment_date, due_date, status, student_id) VALUES (300,  TO_TIMESTAMP('2019/11/11 11:11:11','yyyy/mm/dd hh24:mi:ss'), TO_TIMESTAMP('2019/11/12 12:12:12','yyyy/mm/dd hh24:mi:ss') , 'PAID', 1009);
INSERT INTO Payment (price, payment_date, due_date, status, student_id) VALUES (350,  NULL, TO_TIMESTAMP('2020/02/02 20:20:20','yyyy/mm/dd hh24:mi:ss') , 'NOT PAID', 1010);
INSERT INTO Payment (price, payment_date, due_date, status, student_id) VALUES (325,  TO_TIMESTAMP('2020/03/03 03:03:03','yyyy/mm/dd hh24:mi:ss'), TO_TIMESTAMP('2020/03/04 07:07:07','yyyy/mm/dd hh24:mi:ss') , 'PAID', 1011);
INSERT INTO Payment (price, payment_date, due_date, status, student_id) VALUES (360,  NULL, TO_TIMESTAMP('2020/07/05 06:14:14','yyyy/mm/dd hh24:mi:ss') , 'NOT PAID', 1012);
INSERT INTO Payment (price, payment_date, due_date, status, student_id) VALUES (400,  TO_TIMESTAMP('2020/10/10 16:14:14','yyyy/mm/dd hh24:mi:ss'), TO_TIMESTAMP('2020/10/15 15:14:15','yyyy/mm/dd hh24:mi:ss') , 'PAID', 1013);
INSERT INTO Payment (price, payment_date, due_date, status, student_id) VALUES (425,  NULL, TO_TIMESTAMP('2020/11/15 20:20:20','yyyy/mm/dd hh24:mi:ss') , 'NOT PAID', 1014);
INSERT INTO Payment (price, payment_date, due_date, status, student_id) VALUES (450,  TO_TIMESTAMP('2021/01/01 01:01:01','yyyy/mm/dd hh24:mi:ss'), TO_TIMESTAMP('2021/01/02 01:01:01','yyyy/mm/dd hh24:mi:ss') , 'PAID', 1015);
INSERT INTO Payment (price, payment_date, due_date, status, student_id) VALUES (475,  NULL, TO_TIMESTAMP('2021/04/04 14:11:13','yyyy/mm/dd hh24:mi:ss') , 'NOT PAID', 1016);
INSERT INTO Payment (price, payment_date, due_date, status, student_id) VALUES (500,  TO_TIMESTAMP('2021/07/08 15:12:12','yyyy/mm/dd hh24:mi:ss'), TO_TIMESTAMP('2020/07/09 12:12:14','yyyy/mm/dd hh24:mi:ss') , 'PAID', 1017);
INSERT INTO Payment (price, payment_date, due_date, status, student_id) VALUES (525,  NULL, TO_TIMESTAMP('2021/08/08 07:07:07','yyyy/mm/dd hh24:mi:ss') , 'NOT PAID', 1018);
INSERT INTO Payment (price, payment_date, due_date, status, student_id) VALUES (550,  TO_TIMESTAMP('2021/09/09 09:09:09','yyyy/mm/dd hh24:mi:ss'), TO_TIMESTAMP('2021/09/10 12:12:14','yyyy/mm/dd hh24:mi:ss') , 'PAID', 1019);
INSERT INTO Payment (price, payment_date, due_date, status, student_id) VALUES (575,  NULL, TO_TIMESTAMP('2021/10/11 12:15:16','yyyy/mm/dd hh24:mi:ss') , 'NOT PAID', 1020);

select * from view_emp;
select * from view_std;
select * from Salary;
select * from Department;
select * from Payment;
select * from Room;
select * from Service;
select * from Repair_Service;
select * from Room_Cleaning_Service;